let mock = [{
    id: 1,
    club: "FC Bayern Munich",
    group: "A",
    location: "Munich, Germany",
    league: "Bundesliga",
    titles: "5",
    mostRecentWin: "2020",
    topScorer: "Robert Lewandowski",
    eliminated: false,
  },
  {
      id: 2, 
      club: "Atletico Madrid",
      group: "A",
      location: "Madrid, Spain",
      league: "La Liga",
      titles: "0",
      mostRecentWin: "None",
      topScorer: "Joao Felix",
      eliminated: false,
  },
  {
    id: 3, 
    club: "Red Bull Salzburg",
    group: "A",
    location: "Salzburg, Austria",
    league: "Austrian Bundesliga",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Zlatko Junuzovic",
    eliminated: true,
  },
  {
    id: 4, 
    club: "Lokomotiv Moscow",
    group: "A",
    location: "Moscow, Russia",
    league: "Russian Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Anton Miranchuk",
    eliminated: true,
  },
  {
    id: 5, 
    club: "Real Madrid",
    group: "B",
    location: "Madrid, Spain",
    league: "La Liga",
    titles: "13",
    mostRecentWin: "2018",
    topScorer: "Karim Benzema",
    eliminated: false,
  },
  {
    id: 6, 
    club: "Borussia Monchengladbach",
    group: "B",
    location: "Monchengladback, Germany",
    league: "Bundesliga",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Alassane Plea",
    eliminated: false,
  },
  {
    id: 7, 
    club: "Shakhtar Donetsk",
    group: "B",
    location: "Donetsk, Ukraine",
    league: "Ukranian Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Manor Solomon",
    eliminated: true,
  },
  {
    id: 8, 
    club: "Inter Milan",
    group: "B",
    location: "Milan, Italy",
    league: "Serie A",
    titles: "3",
    mostRecentWin: "2010",
    topScorer: "Romelu Lukaku",
    eliminated: true,
  },
  {
    id: 9, 
    club: "Manchester City",
    group: "C",
    location: "Manchester, England",
    league: "Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Ferran Torres",
    eliminated: false,
  },
  {
    id: 10, 
    club: "FC Porto",
    group: "C",
    location: "Porto, Portugal",
    league: "Primeira Liga",
    titles: "2",
    mostRecentWin: "2004",
    topScorer: "Sergio Oliveira",
    eliminated: false,
  },
  {
    id: 11, 
    club: "Olympiacos",
    group: "C",
    location: "Athens, Greece",
    league: "Super League Greece",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Ahmed Hassan",
    eliminated: true,
  },
  {
    id: 12, 
    club: "Olympique de Marseille",
    group: "C",
    location: "Marseille, France",
    league: "Ligue 1",
    titles: "1",
    mostRecentWin: "1993",
    topScorer: "Dimitri Payet",
    eliminated: true,
  },
  {
    id: 13, 
    club: "Liverpool FC",
    group: "D",
    location: "Liverpool, England",
    league: "Permier League",
    titles: "6",
    mostRecentWin: "2019",
    topScorer: "Mohamed Salah",
    eliminated: false,
  },
  {
    id: 14, 
    club: "Atalanta",
    group: "D",
    location: "Bergamo, Lombardy, Italy",
    league: "Serie A",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Duvan Zapata",
    eliminated: false,
  },
  {
    id: 15, 
    club: "AFC Ajax",
    group: "D",
    location: "Amsterdam, Netherlands",
    league: "Eredivisie",
    titles: "4",
    mostRecentWin: "1995",
    topScorer: "Dusan Tadic",
    eliminated: true,
  },
  {
    id: 16, 
    club: "Midtjylland",
    group: "D",
    location: "Herning, Denmark",
    league: "Danish Superliga",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Alexander Scholz",
    eliminated: true,
  },
  {
    id: 17, 
    club: "Chelsea FC",
    group: "E",
    location: "London, England",
    league: "Permier League",
    titles: "1",
    mostRecentWin: "2012",
    topScorer: "Olivier Giroud",
    eliminated: false,
  },
  {
    id: 18, 
    club: "Sevilla",
    group: "E",
    location: "Seville, Spain",
    league: "La Liga",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Youssef En-Nesyri",
    eliminated: false,
  },
  {
    id: 19, 
    club: "FC Krasnodar",
    group: "E",
    location: "Krasnodar, Russia",
    league: "Russian Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Marcus Berg",
    eliminated: true,
  },
  {
    id: 20, 
    club: "Stade Rennais FC",
    group: "E",
    location: "Rennes, France",
    league: "Ligue 1",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Sehrou Guirassy",
    eliminated: true,
  },
  {
    id: 21, 
    club: "Borussia Dortmund",
    group: "F",
    location: "Dortmund, Germany",
    league: "Bundesliga",
    titles: "1",
    mostRecentWin: "1997",
    topScorer: "Erling Haaland",
    eliminated: false,
  },
  {
    id: 22, 
    club: "SS Lazio",
    group: "F",
    location: "Rome, Italy",
    league: "Serie A",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Ciro Immobile",
    eliminated: false,
  },
  {
    id: 23, 
    club: "Club Brugge KV",
    group: "F",
    location: "Bruges, Belgium",
    league: "Belgian First Division A",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Hans Vanaken",
    eliminated: true,
  },
  {
    id: 24, 
    club: "FC Zenit St. Petersburg",
    group: "F",
    location: "St. Petersburg, Russia",
    league: "Russian Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Artem Dzyuba",
    eliminated: true,
  },
  {
    id: 25, 
    club: "Juventus FC",
    group: "G",
    location: "Turin, Italy",
    league: "Serie A",
    titles: "2",
    mostRecentWin: "1996",
    topScorer: "Alvaro Morata",
    eliminated: false,
  },
  {
    id: 26, 
    club: "FC Barcelona",
    group: "G",
    location: "Barcelona, Spain",
    league: "La Liga",
    titles: "5",
    mostRecentWin: "2015",
    topScorer: "Lionel Messi",
    eliminated: false,
  },
  {
    id: 27, 
    club: "FC Dynamo Kyiv",
    group: "G",
    location: "Kyiv, Ukraine",
    league: "Ukranian Premier League",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Viktor Tsygankov",
    eliminated: true,
  },
  {
    id: 28, 
    club: "Ferencvarosi TC",
    group: "G",
    location: "Ferencvaros, Hungary",
    league: "NB I",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Franck Boli",
    eliminated: true,
  },
  {
    id: 29, 
    club: "Paris Saint-Germain FC",
    group: "H",
    location: "Paris, France",
    league: "Ligue 1",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Kylian Mbappe",
    eliminated: false,
  },
  {
    id: 30, 
    club: "RB Leipzig",
    group: "H",
    location: "Leipzig, Germany",
    league: "Bundesliga",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Angelino",
    eliminated: false,
  },
  {
    id: 31, 
    club: "Manchester United",
    group: "H",
    location: "Manchester, England",
    league: "Premier League",
    titles: "3",
    mostRecentWin: "2008",
    topScorer: "Marcus Rashford",
    eliminated: true,
  },
  {
    id: 32, 
    club: "Istanbul Basaksehir",
    group: "H",
    location: "Istanbul, Turkey",
    league: "Super Lig",
    titles: "0",
    mostRecentWin: "None",
    topScorer: "Irfan Can Kahveci",
    eliminated: true,
  },

]

export default mock;
